version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/source/
permissions:
  - object: /home/ubuntu/source
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300