version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/source/
permissions:
  - object: /home/ubuntu/source/
    mode: 777
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 3000
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300